# Generated by Django 4.1.7 on 2023-03-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Имя')),
                ('surname', models.CharField(max_length=66, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=99, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Тур')),
                ('description', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('images', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
